# jekyll의 환경설정을 위한 Option들 입니다.
# 아래 Option들은 터미널에서 jekyll을 실행할 때 플래그로 지정할 수 있습니다.
# 환경설정 파일에 탭 문자를 사용하지 마세요

# 사이트 변수: site.title 과 같은 방식으로 사용된다.
title: JAE의 개인 기술 블로그
description: JAE의 개인 기술 블로그 입니다.

# For more see: http://jekyllrb-ko.github.io/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 


# 다음은 Jekyll 의 환경설정 옵션들에 대한 디폴트 값 목록입니다.
# @see: http://jekyllrb-ko.github.io/docs/configuration/#section-4

# 파일 종류별 위치
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# 읽기 처리방법
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 컨텐츠 필터링
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# 플러그인
whitelist: []
gems:      []

# 변환
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# 서버 작동
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# 출력 방식
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# 마크다운 처리기
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style