# jekyll의 환경설정을 위한 Option들 입니다.
# 아래 Option들은 터미널에서 jekyll을 실행할 때 플래그로 지정할 수 있습니다.
# 환경설정 파일에 탭 문자를 사용하지 마세요

# 사이트 변수: site.title 과 같은 방식으로 사용된다.
title: JAE의 기술 블로그
url: https://rtfmplz.github.io
description: |
  JAE의 개인 기술 블로그 입니다.
  개인적으로 공부한 내용들을 기록하기 위한 블로그 입니다.
  책 또는 기술 문서를 정리하거나, 개인적인 문제 해결 경험 등을 위주로 포스팅 하였습니다.
  잘못된 내용이나 출처가 누락된 부분을 발견하시면 메일 또는 댓글 남겨주세요!! :)

# For more see: http://jekyllrb-ko.github.io/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

# author 정보
author:
    name: Jae Lee
    email: kjlee.ko@gmail.com
    pages: https://rtfmplz.github.io
    linkedin: https://linkedin.com/in/rtfmplz
    github: https://github.com/rtfmplz


# Jekyll 의 환경설정 옵션들에 대한 디폴트 값 목록은 아래 링크에서 확인할 수 있다.
# @see: http://jekyllrb-ko.github.io/docs/configuration/#section-4


markdown: kramdown
paginate: 15

exclude: [node_modules]
gems: [jekyll-paginate, jekyll-sitemap]

sass:
    sass_dir: _sass
    style: compressed