# jekyll의 환경설정을 위한 Option들 입니다.
# 아래 Option들은 터미널에서 jekyll을 실행할 때 플래그로 지정할 수 있습니다.
# 환경설정 파일에 탭 문자를 사용하지 마세요

# 사이트 변수: site.title 과 같은 방식으로 사용된다.
title: JAE의 기술 블로그
description: JAE의 개인 기술 블로그 입니다.

# For more see: http://jekyllrb-ko.github.io/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 

# author 정보
author:
    name: Jae Lee
    email: kjlee.ko@gmail.com
    pages: https://rtfmplz.github.io
    linkedin: https://linkedin.com/in/rtfmplz
    github: https://github.com/rtfmplz


# Jekyll 의 환경설정 옵션들에 대한 디폴트 값 목록은 아래 링크에서 확인할 수 있다.
# @see: http://jekyllrb-ko.github.io/docs/configuration/#section-4

sass:
    sass_dir: _sass
    style: compressed

exclude:
    - node_modules

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

gems:
    - jekyll-sitemap